openapi: 3.1.0
info:
  title: API do app do Entregador
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /providerlogin:
    post:
      summary: Faz o login no app do entregador
      operationId: post-providerlogin
      responses:
        '200':
          description: OK
      description: Login no app
components:
  schemas: {}
