name: Convert YAML to JSON

on:
  push:
    paths:
      - 'reference/api-erp-v2.yaml'  # Caminho para o arquivo YAML
    branches:
      - main  # Ou o branch principal do seu repositório

jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v2

      - name: Instalar yq
        run: |
          sudo apt-get update
          sudo apt-get install -y jq
          wget https://github.com/mikefarah/yq/releases/download/v4.16.1/yq_linux_amd64 -O /usr/bin/yq
          chmod +x /usr/bin/yq

      - name: Converter YAML para JSON
        run: |
          yq eval -o=json reference/api-erp-v2.yaml > reference/api-erp-v2.json

      - name: Commit e push das alterações
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add reference/api-erp-v2.json
          git commit -m 'Atualizar JSON após modificação do YAML'
          git push
